plugins { id 'com.android.application' }
android {
    namespace = 'com.samsung.android.scan3d'
    compileSdk { version = release(37) }
    defaultConfig {
        applicationId = 'com.samsung.android.scan3d'
        minSdk = 28
        targetSdk = 37
        versionCode = 5
        versionName = '0.1.0'
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures { viewBinding = true }
    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packaging { resources.excludes += 'META-INF/INDEX.LIST' }
}
dependencies {
    implementation project(':utils')
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.11.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
    implementation 'io.ktor:ktor-server-cio:3.5.2'
    implementation 'io.ktor:ktor-server-websockets:3.5.2'
    testImplementation 'junit:junit:4.13.2'
}
